# Preload all le immagini nella cartella wallpaper
preload = /home/stopflunky/.config/hypr/wallpaper/octopus.jpeg
preload = /home/stopflunky/.config/hypr/wallpaper/red_desert.jpeg

# Imposta wallpaper per ogni monitor
wallpaper = HDMI-A-1,/home/stopflunky/.config/hypr/wallpaper/octopus.jpeg
wallpaper = eDP-1,/home/stopflunky/.config/hypr/wallpaper/red_desert.jpeg

# Abilita l'IPC per interagire con hyprpaper dinamicamente
ipc = true
